### ISSUE TITLE
npm i hangs with lock

### ISSUE THREAD

**Issue by reach3r** [zarej/Mattermost-Integration-with-Appear.in#1]
After cloning and running `npm i` the process freezes at the following point:
```
/var/opt/mattermost-integrations/appear.in# npm i
[       ...........] - extract:serve-favicon: verb lock using /root/.npm/_locks/staging-407094b78e9d2e0f.lock for /var/opt/mattermost-integrations/appear.in/node_modules/.stag
```
Waiting several minutes does not seem to help.
While researching I found this: https://github.com/Microsoft/vscode/issues/29204
But the workaround does not apply as this is a linux server vm and no VScode is installed.
It might have something to do with VScode being used when writing the code?

Environment:
Debian 8 Jessie
node -v = v8.9.4
npm -v = 5.6.0

**Comment by zarej** [comment]
Very strange, it is true that I developed it with VSCode but it works on my local and 2 servers that I have installed, servers are on Ubunru.
I tried with the same environment like yours just using docker debian:jessie and it works please check:
```bash
root@98452d4cb671:/Mattermost-Integration-with-Appear.in# npm i
added 454 packages in 9.018s
root@98452d4cb671:/Mattermost-Integration-with-Appear.in# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie
root@98452d4cb671:/Mattermost-Integration-with-Appear.in# npm -v
5.6.0
root@98452d4cb671:/Mattermost-Integration-with-Appear.in# node -v
v8.9.4
```

**Comment by reach3r** [comment]
I figured it out....
I set the proxy settings (for our squid proxy) in the .npmrc file in a wrong format. In case you (or someone else) is interested, the correct way in my case is:
```
# cat ~/.npmrc
proxy=http://proxy.domain.tld:3128
https-proxy=http://proxy.domain.tld:3128
```

Sorry for bothering you!
